services:
  next-cash:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: "unless-stopped"

volumes:
  pgdata:
